description: |
  Select the version of Ruby to use. Uses CircleCI's highly cached convenience images built for CI.
  Any available tag from this list can be used: https://hub.docker.com/r/cimg/ruby/tags
parameters:
  tag:
    description: "The `cimg/ruby` Docker image version tag."
    type: string
    default: "2.7"
docker:
  - image: cimg/ruby:<< parameters.tag >>
